<?php
//// ManageSequences.php : Manage sequences in the database;
//// Author: Maxie D. Schmidt (maxieds@gmail.com)
//// Created: 2019.06.15
?>

<!DOCTYPE html>
<html>
<head>
	<title>gtDMMB RNADB Sequences Administration</title>
	<link type="text/css" href="css/main.css" rel="stylesheet" />
	<link type="text/css" href="css/smoothness/jquery-ui-tabs.css" rel="stylesheet" />
	<script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
	<script type="text/javascript" src="js/jquery-ui-1.8.20.custom.min.js"></script>
</head>
<body>

<?php

include_once "Sessions.php";
Sessions::StartSessionTracking();
if(!Sessions::VerifyLogin() || !Sessions::CurrentUserIsSequencesAdmin()) {
     header("Location: Login.php");
     exit();
}

include_once "BackendConfig.php";
include_once "LoginUtils.php";
include_once "DatabaseUtils.php";
include_once "SequenceUtils.php";

include      "NavigationBar.php";
PrintNavBarHTML(SEQS_ADMIN_PAGE);

?>

<h1>Sequences Administration</h1>

<p>
This page is used for administrators in the <i>sequences</i> group to modify active papers and their 
attributes in the papers database. Complete sequence data is specified by a CSV-formatted file generated by the 
<i>RNADB-construction</i> scripts. The corresponding full set of sequence data can be uploaded into the database for 
users of the frontend site by a zip archive file. 
</p>

<?php

$lastDisplayedRID = "";

if(isset($_POST['DeleteSequenceFormHiddenInput'])) {
     $ridToDelete = $_POST['DeleteSequenceFormHiddenInput'];
     $dbCon = DatabaseUtils::ConnectToRNADB();
     $sqlOp = "DELETE FROM " . BackendConfig::DB_SEQUENCES_TBL . 
              " WHERE rid='$ridToDelete';";
     $dbOpResult = DatabaseUtils::DeSQL($sqlOp, $dbCon);
     if($dbOpResult) {
          echo '<span>' . "Former sequence <i>#$ridToDelete</i> deleted successfully!" . "</span><br/>\n\n";
     }
     else {
          echo "<span style=\"color: #ff0000\">Error deleting sequence <i>#$ridToDelete</i> " . 
               "with SQL query ='$sqlOp': " . "<br/>" . mysqli_error($dbCon) . "</span><br/>\n\n";
     }
     DatabaseUtils::CloseRNADBConnection($dbCon);
}
else if(isset($_POST['ModifySequenceDataFormHiddenInput'])) {
     $lastDisplayedRID = $_POST['ModifySequenceDataFormHiddenInput'];
     $paperToAdd = $_POST['ModifySequenceDataFormAddPaperKey'];
     $nextComments = $_POST['ModifySequenceDataFormCommentsText'];
     $modSeqRowData = SequenceUtils::LookupSequenceData('rid', $lastDisplayedRID, true, true);
     if($modSeqRowData && strcmp($_POST['ModifySequenceDataFormHiddenInput'], "")) {
          $currentPapers = explode(",", str_replace(";", ",", $modSeqRowData['papers']));
          if($paperToAdd === "0") {
               SequenceUtils::PrintHTMLError("No new paper chosen to associate with sequence.");
          }
          else if($paperToAdd === "[--CLEAR-ALL-PAPERS--]") {
               $modSeqRowData['papers'] = "";
          }
          else if(in_array($paperToAdd, $currentPapers)) {
               SequenceUtils::PrintHTMLError("Paper key '$paperToAdd' is already associated with the sequence! ");
          }
          else {
               if(in_array("unpublished", $currentPapers)) {
                    $unpubMarkerIdx = array_search("unpublished", $currentPapers, true);
                    unset($currentPapers[$unpubMarkerIdx]);
               }
               if(in_array("submitted", $currentPapers)) {
                    $unpubMarkerIdx = array_search("submitted", $currentPapers, true);
                    unset($currentPapers[$unpubMarkerIdx]);
               }
               array_push($currentPapers, $paperToAdd);
               sort($currentPapers);
               $modSeqRowData['papers'] = join(",", $currentPapers);
               if(strlen($modSeqRowData['papers']) > 0 && $modSeqRowData['papers'][0] == ',') {
                    $modSeqRowData['papers'] = substr($modSeqRowData['papers'], 1);
               }
          }
          $modSeqRowData['notes'] = $nextComments;
          $modSeqRowData['history'] .= ";\nEdited by " . Sessions::GetCurrentUserName() . " on " . strftime("%Y.%m.%d at %R") . ".";
          $sqlUpdateQuery = "UPDATE " . BackendConfig::DB_SEQUENCES_TBL . 
                            " SET papers='" . $modSeqRowData['papers'] . "',notes='" . $modSeqRowData['notes'] . 
                            "',history='" . $modSeqRowData['history'] . "' WHERE rid='$lastDisplayedRID';";
          $dbCon = DatabaseUtils::ConnectToRNADB();
          $dbOpResult = DatabaseUtils::DeSQL($sqlUpdateQuery, $dbCon);
          if($dbOpResult) {
               echo "<span><i>Successfully updated sequence data!</i></span>\n<br/>\n\n";
          }
          else {
               SequenceUtils::PrintHTMLError("Unable to update sequence data: " . mysqli_error($dbCon));
          }
          DatabaseUtils::CloseRNADBConnection($dbCon);
     }
     else {
          SequenceUtils::PrintHTMLError("Unable to modify the given sequence.");
     }
}
else if(isset($_POST['SequenceDataFormHiddenInput'])) {
     // configure options in the sequence add / modify operations below:
     $optStoreFilesInDB = false;
     $optOverwriteFilesInDB = false;
     $optUpdateExistingSeqs = false;
     if(isset($_POST['UploadSequenceFormOptions'])) {
          foreach($_POST['UploadSequenceFormOptions'] as $cboxId) {
               if($cboxId === "StoreFileInDB") {
                    $optStoreFilesInDB = true;
               }
               else if($cboxId === "OverwriteFilesInDB") {
                    $optOverwriteFilesInDB = true;
               }
               else if($cboxId === "ModifyExistingSeqsInDB") {
                    $optUpdateExistingSeqs = true;
               }
          }
     }
     // figure out what to do with the CSV file if it is uploaded:
     if(isset($_FILES['SequenceCSVUploadFiles'])) {
          $csvServerFilePath = $_FILES['SequenceCSVUploadFiles']['tmp_name'];
          $csvLocalFileName = basename($_FILES['SequenceCSVUploadFiles']['name']);
          $csvUploadOK = $_FILES['SequenceCSVUploadFiles']['error'] == UPLOAD_ERR_OK;
          $errorMsg = SequenceUtils::GetFileUploadErrorMsg($_FILES['SequenceCSVUploadFiles']['error']);
          if(!$csvUploadOK) {
               echo "<span style=\"color: #ff0000\"><b>Error uploading CSV <i>$csvLocalFileName</i>: " . $errorMsg . 
                    "</b></span>\n<br/>\n";
          }
          else {
               echo "<span>Uploaded CSV file <i>$csvLocalFileName</i> to server for processing! </span><br/>\n";
               SequenceUtils::ProcessSequenceCSVFile($csvServerFilePath, $optUpdateExistingSeqs, true);
          }
     }
     else {
          echo "<span style=\"color: #ff0000\"><b>No CSV file selected for upload into the database ...</b></span>\n<br/>\n";
     }
     // figure out to do with the zipped files if the user uploads those too:
     if(isset($_FILES['SequenceDataZipUploadFiles']) && $optStoreFilesInDB) {
          $zipServerFilePath = $_FILES['SequenceDataZipUploadFiles']['tmp_name'];
          $zipLocalFileName = basename($_FILES['SequenceDataZipUploadFiles']['name']);
          $zipUploadOK = $_FILES['SequenceDataZipUploadFiles']['error'] == UPLOAD_ERR_OK;
          $errorMsg = SequenceUtils::GetFileUploadErrorMsg($_FILES['SequenceDataZipUploadFiles']['error']);
          if(!$zipUploadOK) {
               echo "<span style=\"color: #ff0000\"><b>Error uploading zipped <i>$csvLocalFileName</i>: " . $errorMsg . 
                    "</b></span>\n<br/>\n";
          }
          else if($optStoreFilesInDB) {
               echo "<span>Uploaded zip archive <i>$zipLocalFileName</i> to server for processing!</span>\n<br/>\n";
               SequenceUtils::ProcessSequenceZipFiles($zipServerFilePath, $optOverwriteFilesInDB, true);
          }
     }
     else {
          echo "<span style=\"color: #ff0000\"><b>No zipped archive file selected for upload ...</b></span>\n<br/>\n";
     }
}

?>

<script type="text/javascript">

function FetchSequenceData(srid) {
     var jsonUserData = {};
     jsonUserData.sequenceRID = srid;
	 $.ajax({
		type: 'POST',
		url: "SequenceUtils.php?getSequenceJSONData",
		data: jsonUserData,
		success: DisplaySequenceDataInTable
	 });
}

function DisplaySequenceDataInTable(phpJSONData) {
     // display all fields of the table in non-editable format:
     $('#DisplaySequenceTable').find('tbody').detach(); // clear the table contents 
     $('#DisplaySequenceTable').append($('<tbody>')); 
     var jsonObj = JSON.parse(phpJSONData);
     for(var dbColumnKey in jsonObj) {
          var columnValue = jsonObj[dbColumnKey];
          if(dbColumnKey == "notes" || dbColumnKey == "history") {
               columnValue.replace("\n", "<br/>");
          }
          $("#DisplaySequenceTable").find('tbody').append("<tr><td><i>" + dbColumnKey + "</i></td><td>" + 
                                                          columnValue + "</td></tr>");
     }
     $('#DisplaySequenceTable').append($('</tbody>'));
     // display the editable sequence fields which should be easy to update without 
     // having to re-run the rnadb-construction script over again:
     $('#ModifySequenceDataFormHiddenInput').prop("value", jsonObj.rid);
     $('#ModifySequenceDataFormSequenceID').html("<i>" + jsonObj.latin_name + "</i> [ACC: " + jsonObj.accession + "]");
     $('#ModifySequenceDataFormAddPaperKey').prop("selectedIndex", 0);
     $('#ModifySequenceDataFormCommentsText').value(jsonObj.notes);
}

</script>

<h2>Active Sequences List:</h2>

We are currently indexing 
<?php
    $seqRowData = NULL;
    if(Sessions::CurrentUserIsSequencesAdmin()) {
        $seqRowData = SequenceUtils::LookupAllSequences();
    }
    $seqRowCount = $seqRowData != NULL ? count($seqRowData) : 0;
    echo " <b><i>$seqRowCount</i></b> ";
?>
sequences in the database. The sequence entries and their relevant summary data are listed in <i>alphabetical order</i> (by Latin name) 
in the table below. This means that the row IDs (RIDs) are not necessarily contiguous in the table/ 
To display (or modify) a particular sequence entry using the forms below, click on the <i>Display</i> button under 
the <i>Operations</i> column associated with the sequence. Similarly, to delete an active sequence entry completely, click on the 
<i>Delete</i> operation button. 

<br/><hr/><br/>

<table style="width:90%; text-align: center;" align="center">
  <tr>
    <th>Sequence No.</th>
    <th>RID</th>
    <th>Latin Name</th>
    <th>Family</th>
    <th>Length</th>
    <th>Accession No.</th>
    <th>Papers</th>
    <th>Operations</th>
    <th></th>
  </tr>

<?php

for($row = 0; $seqRowData && $row < count($seqRowData); $row++) {
     echo "<tr>\n";
     echo "     <td><b><i>&#35;" . sprintf("%04d", $row + 1) . "</i></b></td>\n";
     echo "     <td>" . $seqRowData[$row]['rid'] . "</td>\n";
     echo "     <td>" . $seqRowData[$row]['latin_name'] . "</td>\n";
     echo "     <td>" . $seqRowData[$row]['family'] . "</td>\n";
     echo "     <td>" . $seqRowData[$row]['length'] . "</td>\n";
     echo "     <td>" . $seqRowData[$row]['accession'] . "</td>\n";
     echo "     <td>" . $seqRowData[$row]['papers'] . "</td>\n";
     echo '     <td><button class="DisplaySequenceButton" value="' . $seqRowData[$row]['rid'] . 
          "          \" onclick=\"FetchSequenceData('" . $seqRowData[$row]['rid'] . "')\">Display</button>\n" . 
          "     </td>\n" .
          "     <td>\n" .
          "          <form action=\"ManageSequences.php\" method=\"post\" accept-charset=\"utf-8\">\n" .
          "               <input type=\"hidden\" id=\"DeleteSequenceFormHiddenInput\"" .            
          "                      name=\"DeleteSequenceFormHiddenInput\" value=\"" . $seqRowData[$row]['rid'] . "\" />\n" . 
          "               <input type=\"submit\" value=\"Delete\" />\n" . 
          "         </form>\n" . 
          "     </td>\n";
     echo "</tr>\n";
}

?>

</table>

<h2>Display Active Sequence Fields:</h2>

<table style="width:90%; text-align: left;" align="center" id="DisplaySequenceTable">
  <thead>
    <th>Database Field</th>
    <th>Sequence Value</th> 
  </thead>
  <tbody id="DisplaySequenceTableBody">
  </tbody>
</table>

<h2>Modify (Selected) Sequence Fields:</h2>

<form action="ManageSequences.php" method="post" accept-charset="utf-8" enctype="multipart/form-data">
   <table>
     <tr>
        <td><b>Displayed Sequence: </b></td>
        <td><span id="ModifySequenceDataFormSequenceID"><i>None</i></span></td>
     </tr>
     <tr>
        <td><b>Add Associated Paper to Sequence: </b></td>
        <td>
             <?php
                  echo "<select name=\"ModifySequenceDataFormAddPaperKey\" id=\"ModifySequenceDataFormAddPaperKey\">\n";
                  echo "     <option value=\"0\"> -- Associate New Paper by Key (Pull Down for Options) -- </option>\n";
                  echo "     <option value=\"[--CLEAR-ALL-PAPERS--]\">CLEAR ALL PAPER KEYS (Cannot be restored)</option>\n";
                  $fullPapersList = SequenceUtils::GetFullPapersList();
                  for($si = 0; $si < count($fullPapersList); $si++) {
                       $paperKey = $fullPapersList[$si];
                       echo "     <option value=\"$paperKey\">PAPER: " . SequenceUtils::ExpandPaperKeyField($paperKey) . 
                            " ($paperKey)</option>\n";
                  }
                  echo "</select>\n";
             ?>
        </td>
     </tr>
     <tr>
        <td><b>Update Comments for Sequence: </b></td>
        <td><textarea cols="100" name="ModifySequenceDataFormCommentsText" id="ModifySequenceDataFormCommentsText"></textarea></td>
     </tr>
     <tr>
        <td><b>Modify the Sequence Data: </b></td>
        <td><input type="submit" value="Modify Data!" /></td>
     </tr>
     <tr>
        <td><b>Reset Form Data: </b></td>
        <td><input type="reset" value="Clear Form" /></td>
     </tr>
   </table>
   <input type="hidden" id="ModifySequenceDataFormHiddenInput" name="ModifySequenceDataFormHiddenInput" value="" />
</form>

<?php
     if(strcmp($lastDisplayedRID, "")) {
          echo "<script type=\"text/javascript\">\n";
          echo "     FetchSequenceData('$lastDisplayedRID');\n";
          echo "</script>\n\n";
     }
?>

<h2>Add / Modify Sequences Form:</h2>

<form action="ManageSequences.php" method="post" accept-charset="utf-8" enctype="multipart/form-data">
   <table>
     <tr>
        <td><b>Choose Sequence CSV Files: </b></td>
        <td><input type="file" name="SequenceCSVUploadFiles" id="SequenceCSVUploadFiles" /></td>
     </tr>
     <tr>
        <td><b>Choose Sequence Data Files Zip Archive (Optional): </b></td>
        <td><input type="file" name="SequenceDataZipUploadFiles" id="SequenceDataZipUploadFiles" /></td>
     </tr>
     <tr>
        <td><b>Upload Options: </b></td>
        <td><input type="checkbox" value="StoreFileInDB" name="UploadSequenceFormOptions[]" id="StoreFileInDBOption" /> 
            Store uploaded zipped files on the server<br/>
            <input type="checkbox" value="OverwriteFilesInDB" name="UploadSequenceFormOptions[]" id="OverWriteFilesInDBOption"> 
            Overwrite existing CT and NOP-CT files with the new zip archive contents<br/>
            <input type="checkbox" value="ModifyExistingSeqsInDB" name="UploadSequenceFormOptions[]" id="ModifyExistingSeqsInDBOption"> 
            Update existing sequence data (if this is <i>NOT</i> checked, then modifications to existing sequences are rejected)
        </td>
     </tr>
     <tr>
        <td><b>Add the Selected Sequences to RNADB: </b></td>
        <td><input type="submit" name="submit" value="Add New Sequences!" /></td>
     </tr>
     <tr>
        <td><b>Reset Form Data: </b></td>
        <td><input type="reset" value="Clear Form" /></td>
     </tr>
   </table>
   <input type="hidden" id="SequenceDataFormHiddenInput" name="SequenceDataFormHiddenInput" value="1" />
</form>

</div><!-- tabs-1 -->
</div><!-- tabs -->

<script type="text/javascript">
	$(document).ready(function() {
		$("#tabs").tabs();
	});
	$(window).load(function() {
	    $('#tabs-1').append('<div id="bottomClearDiv" style="clear:both;" class="clear"></div>');
    });
</script>

</body>
</html>
