#!/bin/bash

PYTHON3=`which python3`

GTFPYTHON_INSTALL_PATH="$GTDMMB_HOME/GTFoldPython/Python/PythonLibrarySrc"
GTFPYTHON_INSTALL_LIBS_PATH="$GTDMMB_HOME/GTFoldPython/Python/Lib"
RUNNER_SCRIPT_PATH="$GTDMMB_HOME/RNADB-construction/rna2ndary"

export PYTHONPATH="$GTFPYTHON_INSTALL_PATH:$RUNNER_SCRIPT_PATH"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$GTFPYTHON_INSTALL_PATH"
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$GTFPYTHON_INSTALL_LIBS_PATH"
export DYLD_FALLBACK_LIBRARY_PATH="/usr/lib:/usr/local/lib:$DYLD_FALLBACK_LIBRARY_PATH"

source ~/.bash_profile || source ~/.bashrc
$PYTHON3 $GTFPYTHON_INSTALL_PATH/../Testing/RunBasicInterface.py

exit 0
